crossdev: write profiles/repo_name
PMS requires it, the key in layout.conf isn't enough. Noticed after
pkgcraft rightly complained about it.

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/crossdev b/crossdev
--- a/crossdev
+++ b/crossdev
@@ -1490,6 +1490,12 @@ set_metadata() {
 	$(printf '%b' "${this_manifests}")
 	EOF
 
+	if [[ ! -f "${CROSSDEV_OVERLAY}"/profiles/repo_name ]] ; then
+		cat <<-EOF > "${CROSSDEV_OVERLAY}"/profiles/repo_name || die "could not write ${CROSSDEV_OVERLAY}/profiles/repo_name"
+		${repo_name}
+		EOF
+	fi
+
 	# If there is no repos.conf entry for the output overlay, create one here
 	if [[ -n ${CROSSDEV_OVERLAY_CREATE_REPOS_CONF} ]]; then
 		cat <<-EOF > "${CROSSDEV_OVERLAY_CREATE_REPOS_CONF}" || die "could not create the repo conf"
