crossdev: declare EAPI in profiles/
Declare the EAPI in profiles/, otherwise we're EAPI 0. pkgcraft rightly
complains about this.

* Similar to 9e889bc74012c4d7bedb9f7fa31d6625be93cf3c.
* See also 7f2f74f4e471172ceeceb78913fd8f8c88aa031d in app-eselect/eselect-repository.

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/crossdev b/crossdev
--- a/crossdev
+++ b/crossdev
@@ -1496,6 +1496,12 @@ set_metadata() {
 		EOF
 	fi
 
+	if [[ ! -f "${CROSSDEV_OVERLAY}"/profiles/eapi ]] ; then
+		cat <<-EOF > "${CROSSDEV_OVERLAY}"/profiles/eapi || die "could not write ${CROSSDEV_OVERLAY}/profiles/eapi"
+		${repo_name}
+		EOF
+	fi
+
 	# If there is no repos.conf entry for the output overlay, create one here
 	if [[ -n ${CROSSDEV_OVERLAY_CREATE_REPOS_CONF} ]]; then
 		cat <<-EOF > "${CROSSDEV_OVERLAY_CREATE_REPOS_CONF}" || die "could not create the repo conf"
