crossdev: make sure to always process extra pkgs
For targets which do not go through all stages (like arm-non-eabi), we
end up always exiting early before we get a chance to process the extra
stuff (like gdb).  So allow the extra args to always be processed.

That's the only functional change here.  The rest is finally using proper
if statements and indenting relevant blocks of code.  It's grown too much
at this point to get away with the previous `foo && bar` logic.

Reported-by: David Hendricks <dhendrix@google.com>
Signed-off-by: Mike Frysinger <vapier@gentoo.org>

diff --git a/crossdev b/crossdev
--- a/crossdev
+++ b/crossdev
@@ -905,40 +905,67 @@ USE="${USE} -selinux"
 # only allow UCLIBC_CPU from env, not from make.conf/profile
 export UCLIBC_CPU=${UCLIBC_CPU}
 
-ex_fast || {
+if ! ex_fast ; then
 
-doemerge ${BPKG}
+	# stage 0: binutils
+	doemerge ${BPKG}
 
-is_s1 || exit 0
-if with_headers ; then
-USE="${KUSE} ${USE}" CROSSCOMPILE_OPTS="headers-only" \
-	doemerge ${KPKG} ${KPKG}-quick
-[[ -n ${LPKG} ]] && \
-USE="${LUSE} ${USE}" CROSSCOMPILE_OPTS="headers-only" \
-	doemerge ${LPKG} ${LPKG}-headers
+	# stage1: bare C compiler
+	if is_s1 ; then
+
+		# first install headers if requested
+		if with_headers ; then
+			# install kernel headers (since the C library often uses them)
+			USE="${KUSE} ${USE}" \
+			CROSSCOMPILE_OPTS="headers-only" \
+				doemerge ${KPKG} ${KPKG}-quick
+
+			if [[ -n ${LPKG} ]] ; then
+				# install C library headers
+				USE="${LUSE} ${USE}" \
+				CROSSCOMPILE_OPTS="headers-only" \
+					doemerge ${LPKG} ${LPKG}-headers
+			fi
+		fi
+
+		# then finally get around to the C compiler
+		USE="${GUSE} ${USE} ${GUSE_DISABLE_STAGE_1}" \
+		CROSSCOMPILE_OPTS="bootstrap" \
+			doemerge ${GPKG} ${GPKG}-stage1
+	fi
+
+	# stage2: kernel headers
+	if is_s2 ; then
+		set_eopts_on_pkg_status ${KPKG} crosscompile_opts_headers-only
+
+		USE="${KUSE} ${USE}" \
+		CROSSCOMPILE_OPTS="" \
+			doemerge ${KPKG}
+	fi
+
+	# stage3: full C library (headers/libs/etc...)
+	if is_s3 ; then
+		[[ -z ${LPKG} ]] && die "Invalid target '${CTARGET}': unknown libc"
+
+		set_eopts_on_pkg_status ${LPKG} crosscompile_opts_headers-only
+
+		USE="${LUSE} ${USE}" \
+		CROSSCOMPILE_OPTS="" \
+			doemerge ${LPKG}
+	fi
+
+	# stage4: full compiler (C/C++/etc...)
+	if is_s4 ; then
+		set_eopts_on_pkg_status ${GPKG} crosscompile_opts_bootstrap
+
+		EOPTS="${EOPTS_UP} --newuse"
+		USE="${GUSE} ${USE} ${GUSE_DISABLE_STAGE_2}" \
+			doemerge ${GPKG} ${GPKG}-stage2
+	fi
+
 fi
-USE="${GUSE} ${USE} ${GUSE_DISABLE_STAGE_1}" CROSSCOMPILE_OPTS="bootstrap" \
-	doemerge ${GPKG} ${GPKG}-stage1
 
-is_s2 || exit 0
-set_eopts_on_pkg_status ${KPKG} crosscompile_opts_headers-only
-USE="${KUSE} ${USE}" CROSSCOMPILE_OPTS="" \
-	doemerge ${KPKG}
-
-is_s3 || exit 0
-[[ -z ${LPKG} ]] && die "Invalid target '${CTARGET}': unknown libc"
-set_eopts_on_pkg_status ${LPKG} crosscompile_opts_headers-only
-USE="${LUSE} ${USE}" CROSSCOMPILE_OPTS="" \
-	doemerge ${LPKG}
-
-is_s4 || exit 0
-set_eopts_on_pkg_status ${GPKG} crosscompile_opts_bootstrap
-EOPTS="${EOPTS_UP} --newuse"
-USE="${GUSE} ${USE} ${GUSE_DISABLE_STAGE_2}" \
-	doemerge ${GPKG} ${GPKG}-stage2
-
-}
-
+# all the extra things (like debuggers)
 EOPTS="${EOPTS_UP} --newuse"
 ex_gcc && USE="${GUSE} ${USE}" doemerge ${GPKG} ${GPKG}-extra
 ex_gdb && USE="${DUSE} ${USE}" doemerge ${DPKG}
